export const TN_DISTRICTS = [
  'Ariyalur',
  'Chengalpattu',
  'Chennai',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakurichi',
  'Kanchipuram',
  'Kanyakumari',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Mayiladuthurai',
  'Nagapattinam',
  'Namakkal',
  'Nilgiris',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'Theni',
  'Thoothukudi',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupathur',
  'Tiruppur',
  'Tiruvallur',
  'Tiruvannamalai',
  'Tiruvarur',
  'Vellore',
  'Viluppuram',
  'Virudhunagar',
];

export const TAMIL_NADU_DISTRICTS = TN_DISTRICTS;

export const TN_DISTRICTS_TA = {
  Ariyalur: 'அரியலூர்',
  Chengalpattu: 'செங்கல்பட்டு',
  Chennai: 'சென்னை',
  Coimbatore: 'கோயம்புத்தூர்',
  Cuddalore: 'கடலூர்',
  Dharmapuri: 'தர்மபுரி',
  Dindigul: 'திண்டுக்கல்',
  Erode: 'ஈரோடு',
  Kallakurichi: 'கள்ளக்குறிச்சி',
  Kanchipuram: 'காஞ்சிபுரம்',
  Kanyakumari: 'கன்னியாகுமரி',
  Karur: 'கரூர்',
  Krishnagiri: 'கிருஷ்ணகிரி',
  Madurai: 'மதுரை',
  Mayiladuthurai: 'மயிலாடுதுறை',
  Nagapattinam: 'நாகப்பட்டினம்',
  Namakkal: 'நாமக்கல்',
  Nilgiris: 'நீலகிரி',
  Perambalur: 'பெரம்பலூர்',
  Pudukkottai: 'புதுக்கோட்டை',
  Ramanathapuram: 'இராமநாதபுரம்',
  Ranipet: 'இராணிப்பேட்டை',
  Salem: 'சேலம்',
  Sivaganga: 'சிவகங்கை',
  Tenkasi: 'தென்காசி',
  Thanjavur: 'தஞ்சாவூர்',
  Theni: 'தேனி',
  Thoothukudi: 'தூத்துக்குடி',
  Tiruchirappalli: 'திருச்சிராப்பள்ளி',
  Tirunelveli: 'திருநெல்வேலி',
  Tirupathur: 'திருப்பத்தூர்',
  Tiruppur: 'திருப்பூர்',
  Tiruvallur: 'திருவள்ளூர்',
  Tiruvannamalai: 'திருவண்ணாமலை',
  Tiruvarur: 'திருவாரூர்',
  Vellore: 'வேலூர்',
  Viluppuram: 'விழுப்புரம்',
  Virudhunagar: 'விருதுநகர்',
};

export const COMMON_CROPS = [
  { id: 'paddy', en: 'Paddy', ta: 'நெல்' },
  { id: 'turmeric', en: 'Turmeric', ta: 'மஞ்சள்' },
  { id: 'cotton', en: 'Cotton', ta: 'பருத்தி' },
  { id: 'banana', en: 'Banana', ta: 'வாழை' },
  { id: 'sugarcane', en: 'Sugarcane', ta: 'கரும்பு' },
  { id: 'vegetables', en: 'Vegetables', ta: 'காய்கறிகள்' },
  { id: 'pulses', en: 'Pulses', ta: 'பருப்பு வகைகள்' },
  { id: 'millets', en: 'Millets', ta: 'சிறு தானியங்கள்' },
  { id: 'coconut', en: 'Coconut', ta: 'தென்னை' },
  { id: 'groundnut', en: 'Groundnut', ta: 'நிலக்கடலை' },
];

export const TAMIL_NADU_CROPS = COMMON_CROPS;

export const MILESTONE_MONTHS = [0, 6, 12, 24, 36];

export const PEER_VERIFICATION_MAX_LOG_AGE_DAYS = 30;

export const VERIFICATION_ENTRY_TYPES = [
  { id: 'panchagavya-application', en: 'Panchagavya Application', ta: 'பஞ்சகவ்யா தெளிப்பு' },
  { id: 'jeevamirtham-application', en: 'Jeevamrutham Application', ta: 'ஜீவாமிர்தம் பாசனம்' },
  { id: 'compost-application', en: 'Compost / Vermicompost', ta: 'மண்புழு உரம் / கம்போஸ்ட்' },
  { id: 'bio-pest-control', en: 'Bio-Pest Control (Neem, etc.)', ta: 'இயற்கை பூச்சி விரட்டி தெளிப்பு' },
  { id: 'soil-test', en: 'Soil Testing', ta: 'மண் பரிசோதனை' },
  { id: 'seed-saving', en: 'Traditional Seed Saving', ta: 'பாரம்பரிய விதை சேமிப்பு' },
  { id: 'no-chemical-purchase', en: 'No Chemical Input Pledge', ta: 'இரசாயனம் பயன்படுத்தா உறுதிமொழி' },
  { id: 'photo-evidence', en: 'Farm Photo Evidence', ta: 'பண்ணை புகைப்பட ஆதாரம்' },
  { id: 'other', en: 'Other Practice', ta: 'மற்ற இயற்கை நடைமுறை' },
];

export const PRODUCE_UNITS = [
  { id: 'kg', en: 'Kilogram (kg)', ta: 'கிலோ (kg)' },
  { id: 'quintal', en: 'Quintal (100 kg)', ta: 'குவிண்டால் (100 kg)' },
  { id: 'ton', en: 'Metric Ton', ta: 'டன் (Ton)' },
  { id: 'bunch', en: 'Bunch / தார்', ta: 'கொத்து / தார்' },
  { id: 'piece', en: 'Piece / எண்ணிக்கை', ta: 'எண்ணிக்கை (Piece)' },
  { id: 'litre', en: 'Litre', ta: 'லிட்டர் (Litre)' },
];

